---
title: "Labor Force Survey 2017"
author: "Bieske, Kibsgaard, Laouiti, Tan, Wenyu, Zhang"
date: "26/09/2017"
output: pdf_document
---
#1. Introduction

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load data, echo=FALSE}
library(haven)
alldata <- read_dta("lfsp_jm17_eul.dta")
library(dplyr)
```

#2. Exploratory Data Analysis

## 2.1 Clean dataset
```{r clean dataset}

selected <- alldata %>% select(MARSTA,RELIG11,SEX,AGE,INDE07M,
                            BANDG,ETHGBEUL,HIQUL15D,MPNR02,
                            REGWKR,SC10MMJ,TOTUS2)

#AGE

#SEX

#MARSTA
selected <- selected[!selected$MARSTA==-9,] 

#INDE07M
selected <- selected[!selected$INDE07M==-8,] 

#HIQUL15D
selected <- selected[!selected$HIQUL15D==-8 & !selected$HIQUL15D==-9 & !selected$HIQUL15D==7,] 

#BANDG
selected <- selected[!selected$BANDG==1 & !selected$BANDG==2 & !selected$BANDG==3 & !selected$BANDG==-8 &!selected$BANDG==-9,] 

#MPNR02
selected <-  selected[!selected$MPNR02 ==-8 & !selected$MPNR02 ==-9,]

#REGWKR
selected <- selected[!selected$REGWKR == -8 
                     & !selected$REGWKR ==-9 
                     & !selected$REGWKR ==2,]

#SC10MMJ
selected <- selected[!selected$REGWKR == -8 
                     & !selected$REGWKR ==-9,]

```

```{r}
# Less significant Variables

#temp <- selected %>% group_by(MPNR02) %>% summarise(n())

#RELIG11
selected <- selected[!selected$RELIG11==-8,] 

#ETHGBEUL
selected <- selected[!selected$ETHGBEUL==-8 & !selected$ETHGBEUL==-9,] 

#HIGHO
#selected <- selected[!selected$HIGHO==-8,] 

```


## 2.2 Combine groups of categorical variable

```{r}
# Create dataset qlfs, which combines 
qlfs <- as.data.frame(selected)
#AGE

#SEX


# MARSTA
qlfs$MARSTA <- ifelse(!qlfs$MARSTA==1 & 
                      !qlfs$MARSTA==2, 3 , qlfs$MARSTA)


#INDE07M
qlfs$INDE07M <- ifelse( qlfs$INDE07M  == 1 
                        |qlfs$INDE07M == 2 
                        |qlfs$INDE07M == 3 
                        |qlfs$INDE07M == 4 
                        |qlfs$INDE07M == 6 
                        |qlfs$INDE07M == 9, 4, qlfs$INDE07M)
qlfs$INDE07M <- ifelse( qlfs$INDE07M == 5, 1, qlfs$INDE07M)
qlfs$INDE07M <- ifelse( qlfs$INDE07M == 7, 2, qlfs$INDE07M)
qlfs$INDE07M <- ifelse( qlfs$INDE07M == 8, 3, qlfs$INDE07M)


#HIQUL15D
qlfs$HIQUL15D <- ifelse( qlfs$HIQUL15D == 1
                            &qlfs$HIQUL15D == 2, 1, qlfs$HIQUL15D ) 
qlfs$HIQUL15D <- ifelse( qlfs$HIQUL15D == 3, 2 ,qlfs$HIQUL15D)
qlfs$HIQUL15D <- ifelse( qlfs$HIQUL15D == 4, 3, qlfs$HIQUL15D)
qlfs$HIQUL15D <- ifelse( qlfs$HIQUL15D == 5, 4, qlfs$HIQUL15D)
qlfs$HIQUL15D <- ifelse( qlfs$HIQUL15D == 6, 5, qlfs$HIQUL15D)



#BANDG
value_vec <- c('1.1','1.10','1.11','1.12','1.13','1.14','1.15','1.16','1.17',
               '1.18','1.19','1.2','1.20','1.21','1.22','1.23','1.24','1.25',
               '1.26','1.27','1.28','1.29','1.3','1.30','1.31','1.32','1.33',
               '1.34','1.4','1.5','1.6','1.7','1.8','1.9',
               '2.1','2.10','2.11','2.12','2.13','2.14','2.15','2.16','2.17',
               '2.18','2.19','2.2','2.20','2.21','2.22','2.23','2.24','2.25',
               '2.26','2.27','2.28','2.29','2.3','2.30','2.31','2.32','2.33',
               '2.34','2.4','2.5','2.6','2.7','2.8','2.9',
               "3.10","3.11","3.12","3.13","3.14","3.15","3.16","3.17","3.18",
               "3.19","3.20","3.21","3.22","3.23","3.24","3.25","3.26","3.27",
               "3.28","3.29","3.30","3.31","3.32","3.3","3.4","3.5","3.6",
               "3.7","3.8","3.9","3.2","3.34")
# Annually
a1  <- 0 
a2  <- seq(4249.5,4749.5,500)
a3  <- seq(5499.5,12499.5,1000)
a4  <- 249.5
a5  <- seq(13499.5,19499.5,1000)
a6  <-seq(21499.5,27499.5,3000)
a7  <- 749.5
a8  <- seq(30499.5,39499.5,3000)
a9  <- 41000
a10 <- seq(1249.5,3749.5,500)
annual <- c(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10) 

# Monthly 
m1  <- 0 
m2  <- seq(424.5, 674.5, 50)
m3  <- seq(749.5, 1049.5, 100)
m4  <- 24.5
m5  <- seq(1149.5, 1949.5, 100)
m6  <- 2099.5
m7  <- 74.5
m8  <- 2349.5
m9  <- seq(2749.5, 3749.5, 500)
m10 <- 4000
m11 <- seq(124.5, 374.5, 50)
month_values <- c(m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11)
months_annual <- month_values*12

# Weekly
w1 <- seq(84.5,104.5,10)
w2 <- 117
w3 <- seq(137,487,25)
w4 <- seq(524.5,674.5,50)
# for 3.3 to 3.9
w5 <- seq(14.5,74.5,10)
# for 3.2
w6 <- 5
# for 3.34 weekly 750 or more
w7 <- 750 
week_values <- c(w1,w2,w3,w4,w5,w6,w7)
week_annual <- week_values * 52

# Combine annually, monthly and weekly
salay_all <-c(annual,months_annual,week_annual)
salary_dict <- data.frame(key=value_vec,value=salay_all)
salary_dict$key <- as.character(salary_dict$key)

# Assign mean salary to qlfs$salary according to salary_dict
for (i in 1:nrow(qlfs)){
  qlfs$BANDG[i] <- salary_dict$value[salary_dict$key==qlfs$BANDG[i]]
}
qlfs$BANDG <- as.numeric(qlfs$BANDG)

# MPNR02
qlfs$MPNR02 <- ifelse(qlfs$MPNR02 == 1
                      |qlfs$MPNR02 == 2
                      |qlfs$MPNR02 == 3
                      |qlfs$MPNR02 == 4
                      |qlfs$MPNR02 == 5, 1 , qlfs$MPNR02)
qlfs$MPNR02 <- ifelse(qlfs$MPNR02 == 6
                      |qlfs$MPNR02 == 7
                      |qlfs$MPNR02 == 8 , 2, qlfs$MPNR02)
qlfs$MPNR02 <- ifelse(qlfs$MPNR02 == 9, 3, qlfs$MPNR02)


#REGWKR
if(FALSE){
qlfs$REGWKR <- ifelse(qlfs$REGWKR  == 20
                      |qlfs$REGWKR == 21, 1,qlfs$REGWKR)

qlfs$REGWKR <- ifelse(qlfs$REGWKR  == 1, 2, qlfs$REGWKR)
qlfs$REGWKR <- ifelse(qlfs$REGWKR  ==16
                      |qlfs$REGWKR ==17
                      |qlfs$REGWKR ==18, 3, qlfs$REGWKR)

qlfs$REGWKR <- ifelse(qlfs$REGWKR  == 3
                      |qlfs$REGWKR ==4
                      |qlfs$REGWKR ==5,   4, qlfs$REGWKR)
qlfs$REGWKR <- ifelse(qlfs$REGWKR  == 6,  5, qlfs$REGWKR)
qlfs$REGWKR <- ifelse(qlfs$REGWKR  == 14
                      |qlfs$REGWKR == 15, 6, qlfs$REGWKR)
qlfs$REGWKR <- ifelse(qlfs$REGWKR  == 19, 8, qlfs$REGWKR)
qlfs$REGWKR <- ifelse(qlfs$REGWKR  == 8
                      |qlfs$REGWKR == 9
                      |qlfs$REGWKR == 11 , 9, qlfs$REGWKR)
qlfs$REGWKR <- ifelse(qlfs$REGWKR  ==13, 10 ,qlfs$REGWKR)
qlfs$REGWKR <- ifelse(qlfs$REGWKR  ==12, 11 ,qlfs$REGWKR)
qlfs$REGWKR <- ifelse(qlfs$REGWKR  ==23, 12 ,qlfs$REGWKR)
qlfs$REGWKR <- ifelse(qlfs$REGWKR  ==22, 13 ,qlfs$REGWKR)
}



#SC10MMJ

```

```{r}
#RELIG11
qlfs$RELIG11 <- ifelse(qlfs$RELIG11 == 1, 1 ,2)
#ETHGBEUL
qlfs$ETHGBEUL <- ifelse(  qlfs$ETHGBEUL== 1 
                          |qlfs$ETHGBEUL== 2 
                          |qlfs$ETHGBEUL== 3, 1, qlfs$ETHGBEUL)
qlfs$ETHGBEUL <- ifelse(  qlfs$ETHGBEUL == 5 
                           |qlfs$ETHGBEUL== 6
                           |qlfs$ETHGBEUL== 7
                           |qlfs$ETHGBEUL== 8
                           |qlfs$ETHGBEUL== 9,  2, qlfs$ETHGBEUL)
qlfs$ETHGBEUL <- ifelse( qlfs$ETHGBEUL == 10, 3, qlfs$ETHGBEUL)
qlfs$ETHGBEUL <- ifelse( qlfs$ETHGBEUL == 4
                           |qlfs$ETHGBEUL== 11, 4, qlfs$ETHGBEUL)

# #HIGHO
# qlfs$HIGHO <- ifelse( qlfs$HIGHO  == 1
#                           |qlfs$HIGHO == 2 
#                           |qlfs$HIGHO == 3, 1, qlfs$HIGHO)
# qlfs$HIGHO <- ifelse( qlfs$HIGHO  == 4
#                           |qlfs$HIGHO == 5
#                           |qlfs$HIGHO ==-9, 2, qlfs$HIGHO)

```


## 2.2 Label categorical variables
```{r}
# Create dataset qlfsfac, which change all the categorical variable of qlfs to factor
facQlfs <- as.data.frame(qlfs)

#AGE

#SEX
facQlfs$SEX <- factor( facQlfs$SEX,
                        levels=c(1,2),
                        labels = c('Male','Female'))

# MARSTA
facQlfs$MARSTA <- factor( facQlfs$MARSTA, 
                           levels=c(1,2,3),
                           labels = c('Single','Married','Other'))

#RELIG11
facQlfs$RELIG11 <- factor(facQlfs$RELIG11, 
                           levels=c(1,2),
                           labels = c('No','Yes'))

#INDE07M
facQlfs$INDE07M <- factor( facQlfs$INDE07M,
                            levels = c(1,2,3,4),
                            labels = c('Distribution, hotels and restaurants',
                                       'Banking and Finance',
                                       'Public admin, education, health',
                                       'Other'))

#ETHGBEUL
facQlfs$ETHGBEUL <-factor( facQlfs$ETHGBEUL, 
                            levels = c(1,2,3,4),
                            c('White','Asian','Black','Other')) 

#HIQUL15D
facQlfs$HIQUL15D <- factor( facQlfs$HIQUL15D, 
                             levels = c(1,2,3,4,5), 
                             labels = c('University',
                                        'College',
                                        'Secondary School', 
                                        'Other',
                                        'Non'))
# #HIGHO
# facQlfs$HIGHO <- factor(facQlfs$HIGHO, 
#                          levels=c(1,2),
#                          c('Yes','Other'))

#MPNR02
facQlfs$MPNR02 <- factor(facQlfs$MPNR02,
                         levels=c(1,2,3),
                         c('Under 50',
                           'Under 500',
                           'Over 500'))

#REGWKR
facQlfs$REGWKR <- factor(facQlfs$REGWKR,
                         levels = c(1:13),
                         c('Scotland',
                           'North East',
                           'North West',
                           'Yorkshire and the Humber',
                           'East Midlands',
                           'West Midlands',
                           'East of England',
                           'Wales',
                           'London',
                           'South West',
                           'South East',
                           'Outside UK',
                           'Northern Ireland'))


#SC10MMJ
facQlfs$SC10MMJ <- factor(facQlfs$SC10MMJ,
                          levels=c(1:9),
                          c('Managers, Directors and Senior Officials',
                            'Professional',
                            'Associate Professional and Technical',
                            'Administrative and Secretarial',
                            'Skilled Trades',
                            'Caring, Leisure and Other Service',
                            'Sales and Customer Service',
                            'Process, Plant and Machine Operatives',
                            'Elementary'))
```


#3. Linear Regression
```{r}
# Use factor variables for linear regression
facQlfs.lm <- lm(BANDG ~ HIQUL15D + SEX + 
                   INDE07M + MARSTA + 
                   MPNR02 + SC10MMJ,data=facQlfs)
summary(facQlfs.lm)

```

#4. Analysis and Results



```{r visualisation, out.width="70%",fig.align="center",tidy=TRUE,tidy.opts=list(width.cutoff=60)}
#Visualisation
library(ggplot2)
library(dplyr)

# Bar chart
ggplot(facQlfs, aes(x=SEX,y=BANDG,col=SEX))+geom_boxplot()+labs(title='Salary distribution of Gender',x='Sex')+theme(plot.title = element_text(hjust = 0.5))

ggplot(facQlfs, aes(x=INDE07M,y=BANDG,col=INDE07M))+geom_boxplot()+labs(title='Salary distribution of Industry')+theme(plot.title = element_text(hjust = 0.5), axis.text = element_text(angle= 45, hjust = 0.9))

ggplot(facQlfs, aes(x=MARSTA,y=BANDG,col=MARSTA))+geom_boxplot()+labs(title='Salary distribution of Maritual')+theme(plot.title = element_text(hjust = 0.5))

ggplot(facQlfs, aes(x=HIQUL15D,y=BANDG,col=HIQUL15D))+geom_boxplot()+labs(title='Salary distribution of Industry')+theme(plot.title = element_text(hjust = 0.5), axis.text = element_text(angle= 45, hjust = 0.9))

ggplot(facQlfs, aes(x=MPNR02,y=BANDG,col=MPNR02))+geom_boxplot()+labs(title='Salary distribution of Employee numbers')+theme(plot.title = element_text(hjust = 0.5))

ggplot(facQlfs, aes(x=REGWKR,y=BANDG,col=REGWKR))+geom_boxplot()+labs(title='Salary distribution of Region of work')+theme(plot.title = element_text(hjust = 0.5),axis.text = element_text(angle= 45, hjust = 0.9))

ggplot(facQlfs, aes(x=SC10MMJ,y=BANDG,col=SC10MMJ))+geom_boxplot()+labs(title='Salary distribution of Region of work')+theme(plot.title = element_text(hjust = 0.5),axis.text = element_text(angle= 45, hjust = 0.9))

# Scatter plot
ggplot(facQlfs,aes(x=AGE,y=BANDG,col=SEX))+geom_point()+ labs(title='Annually Salary distribution over age')+ theme(plot.title = element_text(hjust = 0.5))

ggplot(facQlfs, aes(x=AGE,y=BANDG,col=MARSTA))+geom_point(stat='identity')

ggplot(facQlfs, aes(x=AGE,y=BANDG,col=HIQUL15D))+geom_point()+labs(title='Salary distribution of Highest Education',x='Age')+theme(plot.title = element_text(hjust = 0.5))


ggplot(facQlfs, aes(x=AGE,y=BANDG,col=ETHGBEUL))+geom_point()+labs(title='Salary distribution of Industry',x='Age')+theme(plot.title = element_text(hjust = 0.5))

ggplot(facQlfs, aes(x=AGE,y=BANDG,col=MPNR02))+geom_point()+labs(title='Salary distribution of Employee numbers')+theme(plot.title = element_text(hjust = 0.5))


```

#5. Conclusion






#6. References