---
title: "Less Significant Variables"
author: "Wenyu"
date: "28/09/2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# 1. Introduction

This is a temporary file to record the removed mutation of variables after linear regression. For reference only, won't be included in our final report.  

## 2.1 Clean dataset

```{r clean dataset}
# Less Significant Variables


#Marital
selected <- selected[!selected$MARSTA   == -9,] 


#Religion
selected <- selected[!selected$RELIG11  == -8,] 


#Ethnicity 
selected <- selected[!selected$ETHGBEUL == -8 
                    &!selected$ETHGBEUL ==-9,] 

#workRegion
selected <- selected[!selected$REGWKR   == -8 
                     & !selected$REGWKR == -9 
                     & !selected$REGWKR ==  2,]
```


## 2.2 Combine groups of catagorical variables
```{r combine groups}


# Marital
qlfs$MARSTA <- ifelse(!qlfs$MARSTA ==1 & 
                      !qlfs$MARSTA ==2, 3 , qlfs$MARSTA)


#Religion
qlfs$RELIG11 <- ifelse(qlfs$RELIG11 == 1, 1 ,2)


#Ethinicity
qlfs$ETHGBEUL <- ifelse(  qlfs$ETHGBEUL == 1 
                          |qlfs$ETHGBEUL== 2 
                          |qlfs$ETHGBEUL== 3, 1, qlfs$ETHGBEUL)
qlfs$ETHGBEUL <- ifelse(  qlfs$ETHGBEUL == 5 
                         |qlfs$ETHGBEUL == 6
                         |qlfs$ETHGBEUL == 7
                         |qlfs$ETHGBEUL == 8
                         |qlfs$ETHGBEUL == 9,  2, qlfs$ETHGBEUL)
qlfs$ETHGBEUL <- ifelse( qlfs$ETHGBEUL  == 10, 3, qlfs$ETHGBEUL)
qlfs$ETHGBEUL <- ifelse( qlfs$ETHGBEUL  == 4
                         |qlfs$ETHGBEUL == 11, 4, qlfs$ETHGBEUL)


#Regions of workplace
if(FALSE){
qlfs$REGWKR <- ifelse(qlfs$REGWKR  == 20
                      |qlfs$REGWKR == 21, 1, qlfs$REGWKR)

qlfs$REGWKR <- ifelse(qlfs$REGWKR  == 1,  2, qlfs$REGWKR)
qlfs$REGWKR <- ifelse(qlfs$REGWKR  == 16
                      |qlfs$REGWKR == 17
                      |qlfs$REGWKR == 18, 3, qlfs$REGWKR)

qlfs$REGWKR <- ifelse(qlfs$REGWKR  == 3
                      |qlfs$REGWKR == 4
                      |qlfs$REGWKR == 5,  4, qlfs$REGWKR)
qlfs$REGWKR <- ifelse(qlfs$REGWKR  == 6,  5, qlfs$REGWKR)
qlfs$REGWKR <- ifelse(qlfs$REGWKR  == 14
                      |qlfs$REGWKR == 15, 6, qlfs$REGWKR)
qlfs$REGWKR <- ifelse(qlfs$REGWKR  == 19, 8, qlfs$REGWKR)
qlfs$REGWKR <- ifelse(qlfs$REGWKR  == 8
                      |qlfs$REGWKR == 9
                      |qlfs$REGWKR == 11 , 9, qlfs$REGWKR)
qlfs$REGWKR <- ifelse(qlfs$REGWKR  == 13, 10, qlfs$REGWKR)
qlfs$REGWKR <- ifelse(qlfs$REGWKR  == 12, 11, qlfs$REGWKR)
qlfs$REGWKR <- ifelse(qlfs$REGWKR  == 23, 12, qlfs$REGWKR)
qlfs$REGWKR <- ifelse(qlfs$REGWKR  == 22, 13, qlfs$REGWKR)
}
```

## 2.3 Label Catagorical Variables
```{r}
# MARSTA
facQlfs$MARSTA <- factor( facQlfs$MARSTA, 
                           levels=c(1,2,3),
                           labels = c('Single','Married','Other'))

#RELIG11
facQlfs$RELIG11 <- factor(facQlfs$RELIG11, 
                           levels=c(1,2),
                           labels = c('No','Yes'))

#ETHGBEUL
facQlfs$ETHGBEUL <-factor( facQlfs$ETHGBEUL, 
                            levels = c(1,2,3,4),
                            c('White','Asian','Black','Other')) 


#REGWKR
facQlfs$REGWKR <- factor(facQlfs$REGWKR,
                         levels = c(1:13),
                         c('Scotland',
                           'North East',
                           'North West',
                           'Yorkshire and the Humber',
                           'East Midlands',
                           'West Midlands',
                           'East of England',
                           'Wales',
                           'London',
                           'South West',
                           'South East',
                           'Outside UK',
                           'Northern Ireland'))

```

